
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: .
    id: "uptimerobot-exporter"
    binary: "uptimerobot-exporter"
    goos:
      - linux
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"