{
 "title": "Uptime Robot",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Account details",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "uptimerobot_account_details" }
   ]
  },
  {
   "title": "Monitors",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "expr": "uptimerobot_monitors_status" }
   ]
  },
  {
   "title": "Up monitors",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptimerobot_up_monitors" }
   ]
  },
  {
   "title": "Down monitors",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptimerobot_down_monitors" }
   ]
  },
  {
   "title": "Paused monitors",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptimerobot_paused_monitors" }
   ]
  },
  {
   "title": "Response times",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "uptimerobot_response_time", "legendFormat": "{{friendly_name}}" }
   ]
  }
 ]
}